# Eigen values and vectors

The code is hosted at 
https://github.com/bijesh-p/linear-algebra/blob/main/eigen_values.ipynb  
This can be run in colab as 
https://colab.research.google.com/github/bijesh-p/linear-algebra/blob/main/eigen_values.ipynb

## Eigen values of $A$  and $AA^T$

In [23]:

import numpy as np

# Define matrix A
A = np.array([[7, -2], [4, 1]])
print("Matrix A:")
print(A)
print()

# Calculate eigenvalues and eigenvectors of A
A_eigenvalues, A_eigenvectors = np.linalg.eig(A)
print("Eigenvalues of A:", A_eigenvalues)
print("Eigenvectors of A:")
print(A_eigenvectors)
print()

# Calculate SVD of A
U, sigma, Vt = np.linalg.svd(A, full_matrices=True)
print("SVD of A:")
print("Singular values σ:", sigma)
print("Left singular vectors U:")
print(U)
print("Right singular vectors V^T:")
print(Vt)
print()

# Calculate AA^T and its eigenvalues (should match σ²)
AAT = A @ A.T  # Correct matrix multiplication
AAT_eigenvalues, AAT_eigenvectors = np.linalg.eig(AAT)
print("AA^T matrix:")
print(AAT)
print("Eigenvalues of AA^T:", AAT_eigenvalues)
print("Eigenvectors of AA^T:")
print(AAT_eigenvectors)
print()

# Calculate A^T A and its eigenvalues (should also match σ²)
ATA = A.T @ A  # Correct matrix multiplication
ATA_eigenvalues, ATA_eigenvectors = np.linalg.eig(ATA)
print("A^T A matrix:")
print(ATA)
print("Eigenvalues of A^T A:", ATA_eigenvalues)
print("Eigenvectors of A^T A:")
print(ATA_eigenvectors)
print()

# Show the relationship: eigenvalues of AA^T and A^T A = σ²
print("=== RELATIONSHIP VERIFICATION ===")
print("Singular values σ:", sigma)
print("σ² (squares of singular values):", sigma**2)
print("Eigenvalues of AA^T (sorted):", np.sort(AAT_eigenvalues)[::-1])
print("Eigenvalues of A^T A (sorted):", np.sort(ATA_eigenvalues)[::-1])
print()
print("AA^T eigenvalues match σ²?", np.allclose(np.sort(AAT_eigenvalues)[::-1], sigma**2))
print("A^T A eigenvalues match σ²?", np.allclose(np.sort(ATA_eigenvalues)[::-1], sigma**2))
print()

# Show that U columns are eigenvectors of AA^T
print("=== SVD-EIGENVALUE CONNECTION ===")
print("U columns should be eigenvectors of AA^T:")
for i, u_col in enumerate(U.T):
    result = AAT @ u_col
    expected = (sigma[i]**2) * u_col
    print(f"AA^T * U[:,{i}] ≈ σ²[{i}] * U[:,{i}]?", np.allclose(result, expected))

print()
print("V^T rows should be eigenvectors of A^T A:")
for i, v_row in enumerate(Vt):
    result = ATA @ v_row
    expected = (sigma[i]**2) * v_row
    print(f"A^T A * V^T[{i},:] ≈ σ²[{i}] * V^T[{i},:]?", np.allclose(result, expected))

Matrix A:
[[ 7 -2]
 [ 4  1]]

Eigenvalues of A: [5. 3.]
Eigenvectors of A:
[[0.70710678 0.4472136 ]
 [0.70710678 0.89442719]]

SVD of A:
Singular values σ: [8.16227766 1.83772234]
Left singular vectors U:
[[-0.88577931 -0.46410668]
 [-0.46410668  0.88577931]]
Right singular vectors V^T:
[[-0.98708746  0.16018224]
 [ 0.16018224  0.98708746]]

AA^T matrix:
[[53 26]
 [26 17]]
Eigenvalues of AA^T: [66.6227766  3.3772234]
Eigenvectors of AA^T:
[[ 0.88577931 -0.46410668]
 [ 0.46410668  0.88577931]]

A^T A matrix:
[[ 65 -10]
 [-10   5]]
Eigenvalues of A^T A: [66.6227766  3.3772234]
Eigenvectors of A^T A:
[[ 0.98708746  0.16018224]
 [-0.16018224  0.98708746]]

=== RELATIONSHIP VERIFICATION ===
Singular values σ: [8.16227766 1.83772234]
σ² (squares of singular values): [66.6227766  3.3772234]
Eigenvalues of AA^T (sorted): [66.6227766  3.3772234]
Eigenvalues of A^T A (sorted): [66.6227766  3.3772234]

AA^T eigenvalues match σ²? True
A^T A eigenvalues match σ²? True

=== SVD-EIGENVALUE CONNECTION

## Eigen Values and Matrix Polynomials

For a matrix polynomial P(A) = A³ + 2A + I, if λ is an eigenvalue of A, then P(λ) = λ³ + 2λ + 1 is an eigenvalue of P(A).


In [24]:
# Correct way: Use matrix multiplication for A³
A_cubed = np.linalg.matrix_power(A, 3)  # or A @ A @ A
B = A_cubed + 2*A + np.identity(2)

print("Matrix A:")
print(A)
print("\nA³ (matrix power):")
print(A_cubed)
print("\nB = A³ + 2A + I:")
print(B)

B_eigenvalues, B_eigenvectors = np.linalg.eig(B)
print("\nEigenvalues of A:", A_eigenvalues)
print("Eigenvalues of B:", B_eigenvalues) 

# Expected eigenvalues: if λ is eigenvalue of A, then λ³ + 2λ + 1 is eigenvalue of B
expected = A_eigenvalues**3 + 2*A_eigenvalues + 1
print("Expected eigenvalues of B (λ³ + 2λ + 1):", expected)

# Check if they match (accounting for potential ordering differences)
print("\nVerification:")
print("B eigenvalues (sorted):", np.sort(B_eigenvalues))
print("Expected (sorted):", np.sort(expected))
print("Match:", np.allclose(np.sort(B_eigenvalues), np.sort(expected)))

Matrix A:
[[ 7 -2]
 [ 4  1]]

A³ (matrix power):
[[223 -98]
 [196 -71]]

B = A³ + 2A + I:
[[ 238. -102.]
 [ 204.  -68.]]

Eigenvalues of A: [5. 3.]
Eigenvalues of B: [136.  34.]
Expected eigenvalues of B (λ³ + 2λ + 1): [136.  34.]

Verification:
B eigenvalues (sorted): [ 34. 136.]
Expected (sorted): [ 34. 136.]
Match: True
